Prepare repo for npm package
projecttacoma/fhir-spec-tools pull request #3
Opened 2024-07-18 14:35 UTC by elsaperelli

## Summary
This PR adds the necessary code in order to make `fhir-spec-tools` a npm package. Much of this code is modeled after [fqm-execution](https://github.com/projecttacoma/fqm-execution) since it is a npm package.

### New behavior
In order to make `fhir-spec-tools` a npm package, I needed to export the desired objects using an `index.ts` file in the src directory. I also needed to be able to build the package (hence the changes to `package.json`. Finally, I had to export some of the `.json` files so I slightly altered some of the scripts to output `.ts` files rather than `.json` files (is this okay?).

### Code changes
- `.gitignore` / `eslint.config.mjs` - ignores build directory 
- `package.json` / `tsconfig.json` - build stuff
- `src/data/choiceTypes.ts` / `src/data/choice-types.json` / `src/scripts/parseChoiceTypesForResource.ts` - exports object rather than `.json` file, deletes old `.json` file
- `src/data/mandatoryElements.ts` / `src/data/mandatory-elements.json` / `parseMandatoryElements.ts` - exports object rather than `.json` file, deletes old `.json` file
- `src/data/patient-attribute-paths.ts` / `src/data/patient-attribute-paths.json` / `src/data/patient-search-parameters.ts` / `patient-search-parameters.json` / `src/scripts/parseCompartmentDefinition.ts` - exports object rather than `.json` file, deletes old `.json` file
- `src/index.ts` - exports for npm package

## Testing Guidance
- `npm run check`
- `npm run build`
- In order to check the npm package before publishing it, you can do the following:
- In fhir-spec-tools directory: `npm link`
- In bulk-export-app (or some other repo): `npm link fhir-spec-tools`
- See if you can use fhir-spec-tools in code
- I had to change some things around, so confirm functionality is the same and that all changes make sense!

2024-07-18 19:52 UTC, hossenlopp requested changes
If you do an `npm publish --dry-run` you will notice that it includes the parse scripts in the package that it would upload. It would be nice if those weren't included.

2024-07-18 19:54 UTC, hossenlopp commented on package.json
> +    "build/*"
```suggestion
    "build/data/*",
    "build/index.js"
```
This should export exactly what we need.

2024-07-18 19:58 UTC, hossenlopp commented on tsconfig.json
> +    "rootDir": "./src"
I suggest adding `"declaration": true` to this to get typescript `.d.ts` files output with the build. This will help with using data.

2024-07-18 20:00 UTC, hossenlopp commented on package.json
> +    "build/*"
Also will want `build/scripts/types/*` or to move the types to the data directory. If we enable the "declarations" in the tsconfig.

2024-07-19 18:01 UTC, lmd59 approved these changes

2024-07-19 18:24 UTC, merged